/products:
  get:
    summary: "Obtener products"
    tags:
      - "Products"
    description: "Endpoint para obtener la lista de products"
    produces:
      - "application/json"
    responses:
      "200":
        description: "Respuesta exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Registros encontrados"
                data:
                  type: "object"
                  properties:
                    products:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          id:
                            type: "integer"
                            example: 1
                          name:
                            type: "string"
                            example: "administrador"
                          price:
                            type: "decimal"
                            example: 1.00
                          category_id:
                            type: "integer"
                            example: 1
                          deletedAt:
                            type: "string"
                            format: "null"
                            example: null
                          status:
                            type: "boolean"
                            example: true
      "404":
        description: "Registros no encontrados"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Registros no encontrados"
                data:
                  type: "object"
                  properties:
                    products:
                      type: "array"
                      items: {}
                      example: []
      "500":
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
  post:
    summary: "Crear un nuevo Producto"
    tags:
      - "Products" 
    description: "Endpoint para crear un nuevo producto"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "shampoo"
    responses:
      201:
        description: "Creación exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Creación exitosa"
                data:
                  type: "object"
                  properties:
                    producto:
                      type: "object"
                      properties:
                        id:
                          type: "integer"
                          example: 1
                        name:
                          type: "string"
                          example: "administrador"
                        price:
                          type: "decimal"
                          example: 1.00
                        category_id:
                          type: "integer"
                          example: 1
                        deletedAt:
                          type: "string"
                          format: "null"
                          example: null
                        status:
                          type: "boolean"
                          example: true
      400:
        description: "Error en la solicitud"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                errors:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "field"
                      msg:
                        type: "string"
                        example: "product Name is required"
                      path:
                        type: "string"
                        example: "name"
                      location:
                        type: "string"
                        example: "body"
      500:
        description: "Error del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
/products/{id}:
  get:
    summary: "Obtener un producto"
    tags:
      - "Products"
    description: "Endpoint para obtener un producto por su id"
    parameters:
      - in: "path"
        name: "id"
        required: true
        description: "Id del producto"
        schema:
          type: "integer"
    responses:
      200:
        description: "Respuesta exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Registro encontrado"
                data:
                  type: "object"
                  properties:
                    producto:
                      type: "object"
                      properties:
                        id:
                          type: "integer"
                          example: 1
                        name:
                          type: "string"
                          example: "administrador"
                        price:
                          type: "decimal"
                          example: 1.00
                        category_id:
                          type: "integer"
                          example: 1
                        deletedAt:
                          type: "string"
                          format: "null"
                          example: null
                        status:
                          type: "boolean"
                          example: true
      404:
        description: "Registro no encontrado"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Registro no encontrado"
                data:
                  type: "object"
                  properties: {}
      500:
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
  put:
    summary: "Obtener un producto"
    tags:
      - "Products"
    description: "Endpoint para obtener un producto por su id"
    parameters:
      - in: "path"
        name: "id"
        required: true
        description: "Id del producto"
        schema:
          type: "integer"
      - in: "query"
        name: "example-query"
        required: true
        description: "ejemplo para query"
        schema:
          type: "integer"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "jabon de baño"
    responses:
      200:
        description: "Respuesta exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Registro encontrado"
                data:
                  type: "object"
                  properties:
                    producto:
                      type: "object"
                      properties:
                        id:
                          type: "integer"
                          example: 1
                        name:
                          type: "string"
                          example: "administrador"
                        price:
                          type: "decimal"
                          example: 1.00
                        category_id:
                          type: "integer"
                          example: 1
                        deletedAt:
                          type: "string"
                          format: "null"
                          example: null
                        status:
                          type: "boolean"
                          example: true
      400:
        description: "Error en la solicitud"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                errors:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "field"
                      msg:
                        type: "string"
                        example: "producto Name is required"
                      path:
                        type: "string"
                        example: "name"
                      location:
                        type: "string"
                        example: "body"
      404:
        description: "Registro no encontrado para actualizar"
        content:
          application/json:
            schema:
              properties:
                errors:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "field"
                      msg:
                        type: "string"
                        example: "El parametro id : 1, no existe en la base de datos."
                      path:
                        type: "string"
                        example: "id"
                      location:
                        type: "string"
                        example: "param"
      500:
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
  delete:
    summary: "Eliminar un producto"
    tags:
      - "Products"
    description: "Endpoint para eliminar un producto"
    parameters:
      - name: "id"
        in: "path"
        description: "ID del producto a eliminar"
        required: true
        type: "integer"
    responses:
      204:
        description: "producto eliminado exitosamente, no se devuelve contenido"
      404:
        description: "Registro no encontrado para actualizar"
        content:
          application/json:
            schema:
              properties:
                errors:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "field"
                      msg:
                        type: "string"
                        example: "El parametro id : 1, no existe en la base de datos."
                      path:
                        type: "string"
                        example: "id"
                      location:
                        type: "string"
                        example: "param"
      500:
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
