/settings:
  get:
    summary: "Obtener todas las configuraciones"
    tags:
      - "Configuraciones"
    description: "Endpoint para obtener la lista de todas las configuraciones"
    responses:
      "200":
        description: "Respuesta exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuraciones encontradas"
                data:
                  type: "object"
                  properties:
                    settings:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          id:
                            type: "integer"
                            example: 1
                          name:
                            type: "string"
                            example: "Impuesto IVA"
                          formula:
                            type: "integer"
                            example: 15 # or null
                          description:
                            type: "string"
                            example: "Porcentaje de impuesto al valor agregado"
                          deletedAt:
                            type: "string"
                            format: "date-time"
                            example: null # or "2024-07-27T12:00:00.000Z" if deleted
                          status:
                            type: "boolean"
                            example: true
      "500":
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"

  post:
    summary: "Crear una nueva configuración"
    tags:
      - "Configuraciones"
    description: "Endpoint para crear una nueva configuración"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "Tasa de Interés"
              formula:
                type: "integer"
                example: 5 # or null
              description:
                type: "string"
                example: "Tasa de interés anual para préstamos"
              status: # Optional, defaults to true
                type: "boolean"
                example: true
    responses:
      "201":
        description: "Creación exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuración creada exitosamente"
                data:
                  type: "object"
                  properties:
                    setting:
                      type: "object"
                      properties: # Same properties as in GET
                        id:
                          type: "integer"
                          example: 2
                        name:
                          type: "string"
                          example: "Tasa de Interés"
                        formula:
                          type: "integer"
                          example: 5 # or null
                        description:
                          type: "string"
                          example: "Tasa de interés anual para préstamos"
                        deletedAt:
                          type: "string"
                          format: "date-time"
                          example: null
                        status:
                          type: "boolean"
                          example: true
      "400": # ... (validation errors - same as previous examples)
        description: "Error en la solicitud (validación)"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                errors:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "field"
                      msg:
                        type: "string"
                        example: "Name is required" # Or other validation message
                      path:
                        type: "string"
                        example: "name"
                      location:
                        type: "string"
                        example: "body"
      "500":
        description: "Error del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"

/settings/{id}:
  get:
    summary: "Obtener una configuración por ID"
    tags:
      - "Configuraciones"
    description: "Endpoint para obtener una configuración por su ID"
    parameters:
      - in: "path"
        name: "id"
        required: true
        description: "ID de la configuración"
        schema:
          type: "integer"
    responses:
      "200":
        description: "Respuesta exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuración encontrada"
                data:
                  type: "object"
                  properties:
                    setting:
                      type: "object"
                      properties: # Same properties as in GET /settings
                        id:
                          type: "integer"
                          example: 2
                        name:
                          type: "string"
                          example: "Tasa de Interés"
                        formula:
                          type: "integer"
                          example: 5 # or null
                        description:
                          type: "string"
                          example: "Tasa de interés anual para préstamos"
                        deletedAt:
                          type: "string"
                          format: "date-time"
                          example: null
                        status:
                          type: "boolean"
                          example: true
      "404":
        description: "Configuración no encontrada"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuración no encontrada"
                data:
                  type: "object"
                  properties: {}
      "500":
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
  put:
    summary: "Actualizar una configuración"
    tags:
      - "Configuraciones"
    description: "Endpoint para actualizar una configuración"
    parameters:
      - in: "path"
        name: "id"
        required: true
        description: "ID de la configuración a actualizar"
        schema:
          type: "integer"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: "object"
            properties:  # All fields optional for update
              name:
                type: "string"
                example: "Tasa de Interés Actualizada"
              formula:
                type: "integer"
                example: 6 # or null
              description:
                type: "string"
                example: "Nueva descripción de la tasa de interés"
              status:
                type: "boolean"
                example: false
    responses:
      "200":
        description: "Actualización exitosa"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuración actualizada exitosamente"
                data:
                  type: "object"
                  properties:
                    setting:
                      type: "object"
                      properties: # Same as GET /settings/{id}
                        id:
                          type: "integer"
                          example: 2
                        name:
                          type: "string"
                          example: "Tasa de Interés Actualizada"
                        formula:
                          type: "integer"
                          example: 6 # or null
                        description:
                          type: "string"
                          example: "Nueva descripción de la tasa de interés"
                        deletedAt:
                          type: "string"
                          format: "date-time"
                          example: null
                        status:
                          type: "boolean"
                          example: false
      "400": # ... (validation errors - same as POST)
        description: "Error en la solicitud (validación)"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                errors:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "field"
                      msg:
                        type: "string"
                        example: "Name is required" # Or other validation message
                      path:
                        type: "string"
                        example: "name"
                      location:
                        type: "string"
                        example: "body"
      "404":
        description: "Configuración no encontrada"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuración no encontrada"
                data:
                  type: "object"
                  properties: {}
      "500": # ... (server error - same as GET /settings)
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"

  delete:
    summary: "Eliminar una configuración"
    tags:
      - "Configuraciones"
    description: "Endpoint para eliminar una configuración"
    parameters:
      - in: "path"
        name: "id"
        required: true
        description: "ID de la configuración a eliminar"
        schema:
          type: "integer"
    responses:
      "204":
        description: "Configuración eliminada exitosamente (sin contenido)"
      "404":
        description: "Configuración no encontrada"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Configuración no encontrada"
                data:
                  type: "object"
                  properties: {}
      "500": # ... (server error - same as GET /settings)
        description: "Error interno del servidor"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  example: "Contacte con el administrador"
