
export * from './event-registration.interface'
export * from "./attraction.interface";
export * from "./category.interface";
export * from "./charge.interface";
export * from "./concept.interface";
export * from "./contract.interface";
export * from "./departament.interface";
export * from "./empleoyee.interface";
export * from "./empleoyeeAssistance.interface";
export * from "./empleoyeeUser.interface";
export * from "./interfaceService.interface";
export * from "./inventory.interface";
export * from "./paysheet.interface";
export * from "./paysheetDetail.interface";
export * from "./performanceEvaluation.interface";
export * from "./product.interface";
export * from "./restaurant.interface";
export * from "./role.interface";
export * from "./supervisor.interface";
export * from "./supplier.interface";
export * from "./tourist-package.interface";
export * from "./unitMeasurement.interface";
export * from "./user.interface";
export * from "./event.interface";
export * from "./routes.interface";
